# Production Configuration
server.port=${PORT:8080}

# Database (Render will provide DATABASE_URL)
spring.datasource.url=mysql://root:TiZLjjMfClgaOlczJHnwTnbrfARvauXL@shortline.proxy.rlwy.net:24382/railway
spring.datasource.username=shortline.proxy.rlwy.net
spring.datasource.password=TiZLjjMfClgaOlczJHnwTnbrfARvauXL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aaronageorge2@gmail.com
spring.mail.password=jjxqqsewjpfdxbyr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Frontend URL (will be your Render URL)
app.frontend.url=http://localhost:8082

# Logging
logging.level.root=INFO